/**
 * Template: Calibration Skill Output (F17)
 * Authority: Implementation plan — Option C (post-gen calibration)
 *
 * Generates:
 * - CALIBRATE.md  — instructions for user
 * - calibrate rule — instructions for AI agent (per compile target)
 */

import type { TemplateInput } from './types.js';
import type { GeneratedFile } from './types.js';

// ─── CALIBRATE.md (user-facing) ──────────────────────────────────

export function generateCalibrate(input: TemplateInput): GeneratedFile {
    const { projectName } = input;
    const roles = [...input.intake.roles, ...input.intake.autoAddedRoles];

    const content = `# 🔧 Calibrate Agent Team — ${projectName}

Your agent team config was generated from templates based on your intake answers.
For optimal results, let your AI agent scan this repo and customize the config.

## How to Calibrate

1. Open this project in your AI agent (Claude Code / Cursor / Antigravity)
2. Say: **"Calibrate the agent team for this repo"**
3. The agent will:
   - Scan repo structure, package.json, configs, and code patterns
   - Update \`team.md\` PROJECT_FACTS with actual repo details
   - Adjust capability budgets (±20%) based on codebase complexity
   - Add project-specific rules per role
   - Flag missing or over-provisioned roles
4. Review the changes, then run: \`stackmoss check\`

## When to Re-calibrate

- After major tech stack changes
- After adding/removing team members
- After significant scope changes
- After importing into a new repo

## Current Team

| Role | Source |
|:---|:---|
${roles.map((r) => `| ${r} | intake template |`).join('\n')}

## What Gets Updated

| File | What changes |
|:---|:---|
| \`team.md\` | PROJECT_FACTS, role-specific rules |
| \`.claude/rules/*.md\` | Budget adjustments, project-specific constraints |
| \`evals/rubric.md\` | Project-specific criteria section |

> **Note:** The CONSTITUTION rules (governance) are preserved. Only project-specific
> details and calibrations change. The agent will ask before removing any role.
`;

    return { path: 'CALIBRATE.md', content };
}

// ─── Calibrate Rule (agent-facing) ───────────────────────────────

export function generateCalibrateRule(input: TemplateInput): GeneratedFile {
    const { projectName } = input;
    const roles = [...input.intake.roles, ...input.intake.autoAddedRoles];

    const content = `# Calibration Rule — ${projectName}

_Auto-generated by StackMoss. This rule tells the AI agent how to optimize the team config._

## Trigger

When the user says "calibrate", "calibrate team", or "calibrate agent team", perform the following steps.

## Step 1: SCAN

Read and analyze the repository:
- \`package.json\` — tech stack, dependencies, scripts
- \`tsconfig.json\` / build configs — language, module system
- \`Dockerfile\` / \`docker-compose.yml\` — deployment patterns
- \`.github/\` / CI configs — automation, testing
- Directory structure — monorepo vs single, src layout
- README — project description, architecture notes

## Step 2: ANALYZE

From the scan, determine:
- **Tech stack**: frameworks, languages, databases
- **Project size**: file count, estimated LOC
- **Conventions**: naming patterns, folder structure
- **Dependencies**: key libraries and their versions
- **Testing**: test framework, coverage approach

## Step 3: UPDATE team.md

Edit the \`## PROJECT_FACTS\` section with actual repo details:

\`\`\`markdown
## PROJECT_FACTS
- Tech: [detected stack]
- Structure: [monorepo/single]
- Package manager: [npm/pnpm/yarn]
- Test framework: [vitest/jest/etc]
- CI: [github actions/etc]
- Deploy: [docker/vercel/etc]
\`\`\`

## Step 4: ADJUST BUDGETS

Review capability budgets in \`.claude/rules/*.md\`:
- **Small codebase** (<5k LOC): reduce budgets by 20%
- **Large codebase** (>50k LOC): increase budgets by 20%
- **Complex domain**: increase architecture budget
- **Simple CRUD**: reduce architecture, increase implementation

## Step 5: ADD PROJECT RULES

For each role, add 1-3 project-specific rules based on detected patterns:

Example for a Next.js + Prisma project:
- DEV: "Always use Prisma client for database access"
- DEV: "Use App Router (not Pages Router)"
- QA: "Run \`npx prisma validate\` before committing schema changes"

## Step 6: VALIDATE

Run \`stackmoss check\` to verify:
- All constraints still pass
- Word budgets are within limits
- Config is valid

## Step 7: REPORT

List what changed and why:
- Roles added/removed (with justification)
- Budget adjustments
- Project-specific rules added

## CONSTRAINTS

- **Replace-only**: do not inflate total word count beyond +20%
- **Ask before removing** any role from the template
- **Preserve CONSTITUTION** rules — governance stays unchanged
- **Current roles**: ${roles.join(', ')}
`;

    return { path: 'calibrate-rule.md', content };
}

// ─── Combined generator ──────────────────────────────────────────

export function generateCalibration(input: TemplateInput): GeneratedFile[] {
    return [
        generateCalibrate(input),
        generateCalibrateRule(input),
    ];
}
