/**
 * Template: Calibration output
 * Generates:
 * - CALIBRATE.md - user-facing instructions
 * - calibrate-rule.md - agent-facing instructions
 */

import type { TemplateInput, GeneratedFile } from './types.js';

export function generateCalibrate(input: TemplateInput): GeneratedFile {
    const { projectName } = input;
    const roles = [...input.intake.roles, ...input.intake.autoAddedRoles];

    const content = `# Calibrate Agent Team - ${projectName}

Your agent team config was generated from templates based on intake answers.
For best results, let Tech Lead scan this repo, ask follow-up questions, and recalibrate the team before feature delivery.

## How to Calibrate

1. Open this project in your AI runtime of choice.
2. Say: **"Tech Lead, calibrate this StackMoss team for the current repo."**
3. Tech Lead should:
   - scan repo structure, package.json, configs, and code patterns
   - confirm BRD/NORTH_STAR is locked before changing delivery lanes
   - update \`team.md\` PROJECT_FACTS with actual repo details
   - replace the bootstrap calibration status line once facts are verified
   - adjust the team shape for the real stack
   - keep the bootstrap structure of the current runtime intact
   - propose changes to you before applying any config patch
4. Review the changes, then run: \`stackmoss check\`

## Current Team

| Role | Source |
|---|---|
${roles.map((role) => `| ${role} | intake template |`).join('\n')}

## What Gets Updated

| File | What changes |
|---|---|
| \`team.md\` | PROJECT_FACTS, calibration marker, role rules |
| \`CLAUDE.md\` | Claude Code repo-level guidance |
| \`.claude/skills/*/SKILL.md\` | Claude Code role skills |
| \`.cursor/skills/*/SKILL.md\` | Cursor role skills |
| \`AGENTS.md\` | Codex repo-level guidance |
| \`.agent/*\` | Antigravity skills, rules, workflows |
| \`.github/copilot-instructions.md\` | VS Code / Copilot repo guidance |

> Governance rules stay intact. Calibration changes project-specific facts and team shape only.
`;

    return { path: 'CALIBRATE.md', content };
}

export function generateCalibrateRule(input: TemplateInput): GeneratedFile {
    const { projectName } = input;
    const roles = [...input.intake.roles, ...input.intake.autoAddedRoles];

    const content = `# Calibration Rule - ${projectName}

Auto-generated by StackMoss. This rule tells Tech Lead how to optimize the team config without bloating or cross-polluting runtime configs.

## Trigger

When the user says "calibrate", "calibrate team", or "calibrate agent team", follow this sequence.

## Step 1: Read bootstrap sources

- \`team.md\`
- \`FEATURES.md\`
- \`NORTH_STAR.md\`
- \`NON_GOALS.md\`
- Only the bootstrap outputs for the IDE or CLI currently in use

## Step 2: Scan the repo

Read and analyze:
- \`package.json\` and lockfiles
- tsconfig/build configs
- Docker / deployment configs
- CI configs in \`.github/\`
- directory structure
- repo README and ADR-style notes

## Step 3: Ask follow-up questions

- If BRD or NORTH_STAR is not locked, stop implementation planning and turn F1 into locking scope and constraints.
- If commands, paths, deployment targets, or stack choices are unclear, ask focused follow-up questions instead of assuming.

## Step 4: Update team.md

- Replace stale facts in \`PROJECT_FACTS\`
- Replace the bootstrap calibration marker after facts are verified
- Reshape role count or delivery lanes when the real repo requires it
- Keep edits replace-only inside existing sections

## Step 5: Preserve the current runtime structure

- Do not invent alternative folder layouts for the runtime currently in use.
- If you are calibrating Claude Code, stay inside \`CLAUDE.md\` and \`.claude/skills/*\`.
- If you are calibrating Cursor, stay inside \`.cursor/skills/*\`.
- If you are calibrating Codex, stay inside \`AGENTS.md\`.
- If you are calibrating VS Code / Copilot, stay inside \`.github/copilot-instructions.md\`.
- If you are calibrating Antigravity, stay inside \`.agent/*\`.

## Step 6: Report before apply

- List what will change and why
- Ask the user before applying any shared config patch

## Constraints

- Replace-only: do not inflate config with append-only memory logs
- Single writer: only Tech Lead prepares shared team-config patches
- Confirm-first: user approval is required before apply
- Preserve governance rules and keep changes bounded to the current runtime
- Current roles: ${roles.join(', ')}
`;

    return { path: 'calibrate-rule.md', content };
}

export function generateCalibration(input: TemplateInput): GeneratedFile[] {
    return [
        generateCalibrate(input),
        generateCalibrateRule(input),
    ];
}
