/**
 * Compile Layer: Antigravity Target
 * Authority: BRD §15.1, §15.2
 *
 * Antigravity requires ATOMIC capability-level split:
 *   team.md role → 1 file PER capability
 *   [TL-ARCH]    → .agents/skills/tech-lead--arch/SKILL.md
 *   [TL-REVIEW]  → .agents/skills/tech-lead--review/SKILL.md
 *   [DEV-IMPL]   → .agents/skills/developer--impl/SKILL.md
 *
 * Each skill file follows Antigravity format:
 *   - YAML frontmatter: name, description
 *   - Markdown body: When to Use, Rules, Budget
 *
 * Pure function, string interpolation only, no LLM.
 */

import type { GeneratedFile } from '../templates/types.js';
import { extractRoleId } from '../templates/team.js';
import { ROLE_CAPABILITIES } from './claude-code.js';
import { getCapabilitiesForRole } from '../budgets.js';

// ─── Slug Helpers ────────────────────────────────────────────────

/** Map role ID → human-readable name for filenames */
const ROLE_NAME_MAP: Record<string, string> = {
    TL: 'tech-lead',
    BA: 'business-analyst',
    DEV: 'developer',
    QA: 'quality-assurance',
    DOCS: 'documentation',
    SEC: 'security',
    OPS: 'devops',
};

/**
 * Convert capability ID → folder name.
 * e.g. "TL-ARCH" → "tech-lead--arch"
 */
export function capabilityToSlug(capId: string): string {
    const parts = capId.split('-');
    const roleId = parts[0];
    const capSuffix = parts.slice(1).join('-').toLowerCase();
    const roleName = ROLE_NAME_MAP[roleId] ?? roleId.toLowerCase();

    return `${roleName}--${capSuffix}`;
}

// ─── Render SKILL.md ─────────────────────────────────────────────

function renderSkillMd(
    capId: string,
    capName: string,
    budget: number,
    trigger: string,
    doNotUse: string,
    projectName: string,
): string {
    const slug = capabilityToSlug(capId);

    return `---
name: ${slug}
description: ${capName}. ${trigger}
---

# ${capName} — ${projectName}
_Generated by StackMoss. Atomic skill file for Antigravity._

## When to Use
- ${trigger}

## When NOT to Use
- ${doNotUse}

## Budget
- **${budget} words** max per session

## Rules
- Replace-only: content after ≤ content before (word count)
- No new sections — only edit existing content
- Verify before marking done
`;
}

// ─── Compile ─────────────────────────────────────────────────────

/**
 * Compile roles → .agents/skills/<role>--<cap>/SKILL.md
 *
 * Atomic split: 1 capability = 1 skill folder with SKILL.md
 */
export function compileAntigravity(
    roles: string[],
    autoAddedRoles: string[],
    projectName: string,
): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const seen = new Set<string>();

    const allRoles = [...roles, ...autoAddedRoles];

    for (const role of allRoles) {
        const baseId = extractRoleId(role);

        if (seen.has(baseId)) continue;
        seen.add(baseId);

        const def = ROLE_CAPABILITIES[baseId];
        if (!def) {
            // Unknown role → single skill file
            const slug = (ROLE_NAME_MAP[baseId] ?? baseId).toLowerCase();
            files.push({
                path: `.agents/skills/${slug}/SKILL.md`,
                content: `---
name: ${slug}
description: ${role} role for ${projectName}.
---

# ${role} — ${projectName}
_Atomic skill file. Configure capabilities as needed._
`,
            });
            continue;
        }

        // Split each capability into its own skill file
        const allowedCapabilities = new Set(getCapabilitiesForRole(role));
        for (const cap of def.capabilities.filter(
            (item) => allowedCapabilities.size === 0 || allowedCapabilities.has(item.id),
        )) {
            const slug = capabilityToSlug(cap.id);
            files.push({
                path: `.agents/skills/${slug}/SKILL.md`,
                content: renderSkillMd(
                    cap.id,
                    cap.name,
                    cap.budget,
                    cap.trigger,
                    cap.doNotUse,
                    projectName,
                ),
            });
        }
    }

    return files;
}
