/**
 * Compile Layer: Codex target
 * Authority: OpenAI Codex uses AGENTS.md for repo-scoped instructions.
 */

import { extractRoleId } from '../templates/team.js';
import type { GeneratedFile } from '../templates/types.js';

function uniqueRoleIds(roles: string[], autoAddedRoles: string[]): string[] {
    return Array.from(new Set([...roles, ...autoAddedRoles].map(extractRoleId)));
}

export function compileCodex(
    roles: string[],
    autoAddedRoles: string[],
    projectName: string,
): GeneratedFile[] {
    const roleIds = uniqueRoleIds(roles, autoAddedRoles);
    const roleList = roleIds.map((roleId) => `- ${roleId}`).join('\n');

    const content = `# StackMoss Agent Bootstrap - ${projectName}

Codex should treat this repository as a Tech Lead-first workflow.
This file is \`AGENTS.md\` for Codex and should stay at repo scope.

## First Session Policy

- Start by reading \`team.md\`, \`FEATURES.md\`, \`NORTH_STAR.md\`, and \`NON_GOALS.md\`.
- Before real feature delivery, confirm the BRD or \`NORTH_STAR.md\` is locked.
- If the BRD is not locked, turn F1 into locking scope, constraints, and success criteria.
- In an existing repo, act as Tech Lead first: scan the repository, ask follow-up questions if facts are missing, and propose bootstrap corrections before implementation.
- Replace stale facts in existing sections. Never append memory logs to config.
- Ask the user before applying any shared config patch.

## Agent Team

${roleList}

## Tech Lead Protocol

- Tech Lead is the coordinator and single writer for shared team config.
- Other roles can surface verified signals, but they do not rewrite shared config directly.
- If commands, paths, or stack facts are uncertain, ask focused follow-up questions instead of assuming.
- When calibration is complete, update \`team.md\` by replacing the bootstrap calibration marker and stale facts.

_Generated by StackMoss. Edit team.md to change shared project instructions._
`;

    return [{ path: 'AGENTS.md', content }];
}
