/**
 * Compile Layer: Cursor Target
 * Authority: BRD §15, template-engine skill
 *
 * Compile team.md roles → .cursor/rules/<role>.mdc
 * Format: YAML frontmatter (description, globs, alwaysApply) + markdown body
 *
 * Pure function, string interpolation only, no LLM.
 */

import type { GeneratedFile } from '../templates/types.js';
import { extractRoleId } from '../templates/team.js';
import { ROLE_CAPABILITIES, roleToSlug } from './claude-code.js';
import { getCapabilitiesForRole } from '../budgets.js';

// ─── Cursor Rule Types ───────────────────────────────────────────

interface CursorRuleConfig {
    alwaysApply: boolean;
    description: string;
    globs?: string;
}

// Constitution and project facts are always-on
const ALWAYS_ON_RULES: Record<string, CursorRuleConfig> = {
    constitution: {
        alwaysApply: true,
        description: 'Core team rules — always applied to every interaction.',
    },
    'project-facts': {
        alwaysApply: true,
        description: 'Project-specific facts and context.',
    },
    'working-contract': {
        alwaysApply: true,
        description: 'Team working agreements and conventions.',
    },
};

const ALWAYS_ON_RULE_CONTENT: Record<string, string> = {
    constitution: `## Governance Rules
- replace-only: true
- budget-enforcement: hard
- suggest-only: true
- no-destructive-tools: true

## Patch Rules
- Rewrite the existing section only
- Verify after patch apply

## Team Maintenance
- Lock BRD or NORTH_STAR before real implementation work
- Tech Lead is the single writer for shared team config
- Config changes require user confirmation before apply
`,
    'project-facts': `## Environment
- Package manager: TBD
- Run command: TBD
- Build command: TBD
- Test command: TBD

## Tech Stack
- Framework: TBD
- Database: TBD
- Deploy target: TBD
`,
    'working-contract': `## Definition of Done
- Acceptance criteria pass
- QA checklist pass
- TL review approved

## Review Gates
- DEV -> QA -> TL
- Escalate repeated blockers to TL
`,
};

// Role-level rules: agent-requested (AI reads description)
function getRoleConfig(roleId: string, roleName: string): CursorRuleConfig {
    return {
        alwaysApply: false,
        description: `${roleName} capabilities — use when ${roleName.toLowerCase()} tasks are needed.`,
    };
}

// ─── Render .mdc file ────────────────────────────────────────────

function renderMdcFrontmatter(config: CursorRuleConfig): string {
    const lines = ['---'];
    lines.push(`description: "${config.description}"`);
    if (config.globs) {
        lines.push(`globs: "${config.globs}"`);
    }
    lines.push(`alwaysApply: ${config.alwaysApply}`);
    lines.push('---');
    return lines.join('\n');
}

function renderRoleMdc(roleStr: string, projectName: string): string {
    const baseId = extractRoleId(roleStr);
    const def = ROLE_CAPABILITIES[baseId];

    if (!def) {
        const frontmatter = renderMdcFrontmatter({
            alwaysApply: false,
            description: `${roleStr} role for ${projectName}.`,
        });
        return `${frontmatter}\n\n# ${roleStr} — ${projectName}\n\n_Role configuration. Define capabilities as needed._\n`;
    }

    const frontmatter = renderMdcFrontmatter(getRoleConfig(baseId, def.name));
    const allowedCapabilities = new Set(getCapabilitiesForRole(roleStr));

    const capLines = def.capabilities
        .filter((cap) => allowedCapabilities.size === 0 || allowedCapabilities.has(cap.id))
        .map((cap) =>
        `### ${cap.id}: ${cap.name}
- **Budget:** ${cap.budget} words
- **Trigger:** ${cap.trigger}
- **Do NOT use:** ${cap.doNotUse}`,
    ).join('\n\n');

    const maintenanceLines = baseId === 'TL'
        ? [
            'Confirm BRD or NORTH_STAR is locked before implementation.',
            'Recalibrate the team after BRD lock and repo scan.',
            'Prepare replace-only config patches and ask the user before apply.',
        ]
        : [
            'Do not edit shared team config directly.',
            'Send verified command/path/test signals to Tech Lead.',
            'Never append logs or memory notes into config.',
        ];

    return `${frontmatter}

# ${def.name} — ${projectName}
_Generated by StackMoss. Edit team.md to change, then recompile._

## Capabilities

${capLines}

## Config Maintenance
${maintenanceLines.map((line) => `- ${line}`).join('\n')}
`;
}

// ─── Compile ─────────────────────────────────────────────────────

/**
 * Compile roles → .cursor/rules/<role-slug>.mdc
 * Plus always-on rules for constitution/facts/contract.
 */
export function compileCursor(
    roles: string[],
    autoAddedRoles: string[],
    projectName: string,
): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // 1. Always-on rules (placeholders — filled by template engine at generation time)
    for (const [ruleId, config] of Object.entries(ALWAYS_ON_RULES)) {
        const frontmatter = renderMdcFrontmatter(config);
        files.push({
            path: `.cursor/rules/${ruleId}.mdc`,
            content: `${frontmatter}\n\n# ${ruleId.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())} — ${projectName}\n\n${ALWAYS_ON_RULE_CONTENT[ruleId]}`,
        });
    }

    // 2. Role-specific rules
    const seen = new Set<string>();
    const allRoles = [...roles, ...autoAddedRoles];

    for (const role of allRoles) {
        const baseId = extractRoleId(role);
        if (!seen.has(baseId)) {
            seen.add(baseId);
            files.push({
                path: `.cursor/rules/${roleToSlug(role)}.mdc`,
                content: renderRoleMdc(role, projectName),
            });
        }
    }

    return files;
}
