/**
 * Compile Layer: Cursor Target
 * Authority: BRD §15, template-engine skill
 *
 * Compile team.md roles → .cursor/rules/<role>.mdc
 * Format: YAML frontmatter (description, globs, alwaysApply) + markdown body
 *
 * Pure function, string interpolation only, no LLM.
 */

import type { GeneratedFile } from '../templates/types.js';
import { extractRoleId } from '../templates/team.js';
import { ROLE_CAPABILITIES, roleToSlug } from './claude-code.js';

// ─── Cursor Rule Types ───────────────────────────────────────────

interface CursorRuleConfig {
    alwaysApply: boolean;
    description: string;
    globs?: string;
}

// Constitution and project facts are always-on
const ALWAYS_ON_RULES: Record<string, CursorRuleConfig> = {
    constitution: {
        alwaysApply: true,
        description: 'Core team rules — always applied to every interaction.',
    },
    'project-facts': {
        alwaysApply: true,
        description: 'Project-specific facts and context.',
    },
    'working-contract': {
        alwaysApply: true,
        description: 'Team working agreements and conventions.',
    },
};

// Role-level rules: agent-requested (AI reads description)
function getRoleConfig(roleId: string, roleName: string): CursorRuleConfig {
    return {
        alwaysApply: false,
        description: `${roleName} capabilities — use when ${roleName.toLowerCase()} tasks are needed.`,
    };
}

// ─── Render .mdc file ────────────────────────────────────────────

function renderMdcFrontmatter(config: CursorRuleConfig): string {
    const lines = ['---'];
    lines.push(`description: "${config.description}"`);
    if (config.globs) {
        lines.push(`globs: "${config.globs}"`);
    }
    lines.push(`alwaysApply: ${config.alwaysApply}`);
    lines.push('---');
    return lines.join('\n');
}

function renderRoleMdc(roleStr: string, projectName: string): string {
    const baseId = extractRoleId(roleStr);
    const def = ROLE_CAPABILITIES[baseId];

    if (!def) {
        const frontmatter = renderMdcFrontmatter({
            alwaysApply: false,
            description: `${roleStr} role for ${projectName}.`,
        });
        return `${frontmatter}\n\n# ${roleStr} — ${projectName}\n\n_Role configuration. Define capabilities as needed._\n`;
    }

    const frontmatter = renderMdcFrontmatter(getRoleConfig(baseId, def.name));

    const capLines = def.capabilities.map((cap) =>
        `### ${cap.id}: ${cap.name}
- **Budget:** ${cap.budget} words
- **Trigger:** ${cap.trigger}
- **Do NOT use:** ${cap.doNotUse}`,
    ).join('\n\n');

    return `${frontmatter}

# ${def.name} — ${projectName}
_Generated by StackMoss. Edit team.md to change, then recompile._

## Capabilities

${capLines}
`;
}

// ─── Compile ─────────────────────────────────────────────────────

/**
 * Compile roles → .cursor/rules/<role-slug>.mdc
 * Plus always-on rules for constitution/facts/contract.
 */
export function compileCursor(
    roles: string[],
    autoAddedRoles: string[],
    projectName: string,
): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // 1. Always-on rules (placeholders — filled by template engine at generation time)
    for (const [ruleId, config] of Object.entries(ALWAYS_ON_RULES)) {
        const frontmatter = renderMdcFrontmatter(config);
        files.push({
            path: `.cursor/rules/${ruleId}.mdc`,
            content: `${frontmatter}\n\n# ${ruleId.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())} — ${projectName}\n\n_Section from team.md. Synced by StackMoss._\n`,
        });
    }

    // 2. Role-specific rules
    const seen = new Set<string>();
    const allRoles = [...roles, ...autoAddedRoles];

    for (const role of allRoles) {
        const baseId = extractRoleId(role);
        if (!seen.has(baseId)) {
            seen.add(baseId);
            files.push({
                path: `.cursor/rules/${roleToSlug(role)}.mdc`,
                content: renderRoleMdc(role, projectName),
            });
        }
    }

    return files;
}
