/**
 * Migration Report Renderer — ScanResult → MIGRATION_REPORT.md
 * Authority: BRD §9.5
 *
 * Renders the 3-tier report: FACTS, HYPOTHESES, OPEN QUESTIONS.
 * Budget: ≤ 700 words (BRD §9.1 budgets.migrationReport)
 */

import type { ScanResult } from './types.js';

export const MIGRATION_REPORT_FILENAME = 'MIGRATION_REPORT.md';

export function renderMigrationReport(
    projectName: string,
    scanResult: ScanResult,
): string {
    const lines: string[] = [];

    lines.push(`# Migration Report — ${projectName}`);
    lines.push('_Generated by stackmoss inject. Reviewed by human before promote._');
    lines.push('');

    // ── FACTS ────────────────────────────────────────────────
    lines.push('## FACTS (confidence: high)');
    lines.push('> Những gì đã được verify từ file thực tế trong repo.');
    lines.push('');

    if (scanResult.facts.length === 0) {
        lines.push('_No facts detected — this repo may be empty or have no recognizable config files._');
    } else {
        for (const fact of scanResult.facts) {
            lines.push(`- **${fact.category}:** ${fact.value} (from ${fact.source})`);
        }
    }
    lines.push('');

    // ── HYPOTHESES ───────────────────────────────────────────
    lines.push('## HYPOTHESES (confidence: medium, cần verify)');
    lines.push('> Những gì StackMoss suy đoán nhưng chưa chắc.');
    lines.push('');

    if (scanResult.hypotheses.length === 0) {
        lines.push('_No hypotheses generated._');
    } else {
        for (const hyp of scanResult.hypotheses) {
            const criticalTag = hyp.critical ? ' ⚠️ CRITICAL' : '';
            lines.push(
                `- **${hyp.category}:** ${hyp.value} ` +
                `(confidence: ${hyp.confidence}%)${criticalTag} — from ${hyp.source}`,
            );
        }
    }
    lines.push('');

    // ── OPEN QUESTIONS ───────────────────────────────────────
    lines.push('## OPEN QUESTIONS (cần human confirm trước khi promote)');
    lines.push('');

    const unresolvedQuestions = scanResult.openQuestions.filter((q) => !q.resolved);
    const resolvedQuestions = scanResult.openQuestions.filter((q) => q.resolved);

    if (unresolvedQuestions.length === 0 && resolvedQuestions.length === 0) {
        lines.push('_No open questions — all clear for promote._');
    } else {
        if (unresolvedQuestions.length > 0) {
            for (const q of unresolvedQuestions) {
                lines.push(`- [ ] **[${q.id}]** ${q.text} _(${q.impact})_`);
            }
        }

        if (resolvedQuestions.length > 0) {
            lines.push('');
            lines.push('### Đã trả lời');
            for (const q of resolvedQuestions) {
                lines.push(`- [x] **[${q.id}]** ${q.text} → ${q.answer ?? '(confirmed)'}`);
            }
        }
    }
    lines.push('');

    // ── Footer ───────────────────────────────────────────────
    lines.push('---');
    lines.push('');
    lines.push('_Sau khi resolve hết OPEN QUESTIONS → chạy `stackmoss promote --confirm`_');
    lines.push('');

    return lines.join('\n');
}

/**
 * Parse an existing MIGRATION_REPORT.md to extract question states.
 * Used by `resolve` and `promote` commands.
 */
export interface ParsedReport {
    hasUnresolvedQuestions: boolean;
    unresolvedCount: number;
    resolvedCount: number;
    hasCriticalLowConfidence: boolean;
    /** Raw lines for manipulation by resolve */
    rawContent: string;
}

export function parseMigrationReport(content: string): ParsedReport {
    const unresolvedMatches = content.match(/^- \[ \] \*\*\[/gm);
    const resolvedMatches = content.match(/^- \[x\] \*\*\[/gm);

    // Check for critical hypotheses with low confidence
    const criticalLowConfidence = /\(confidence: (\d+)%\)\s*⚠️ CRITICAL/g;
    let hasCriticalLowConfidence = false;
    let match: RegExpExecArray | null;
    while ((match = criticalLowConfidence.exec(content)) !== null) {
        if (parseInt(match[1], 10) < 80) {
            hasCriticalLowConfidence = true;
            break;
        }
    }

    const unresolvedCount = unresolvedMatches?.length ?? 0;
    const resolvedCount = resolvedMatches?.length ?? 0;

    return {
        hasUnresolvedQuestions: unresolvedCount > 0,
        unresolvedCount,
        resolvedCount,
        hasCriticalLowConfidence,
        rawContent: content,
    };
}
