/**
 * Migration Report Renderer -> ScanResult => MIGRATION_REPORT.md
 * Authority: BRD §9.5
 */

import type { ScanResult } from './types.js';

export const MIGRATION_REPORT_FILENAME = 'MIGRATION_REPORT.md';

function getSection(content: string, heading: string): string {
    const lines = content.split('\n');
    const startIndex = lines.findIndex((line) => line.startsWith(`## ${heading}`));

    if (startIndex === -1) {
        return '';
    }

    let endIndex = lines.length;
    for (let index = startIndex + 1; index < lines.length; index++) {
        if (lines[index].startsWith('## ')) {
            endIndex = index;
            break;
        }
    }

    return lines.slice(startIndex, endIndex).join('\n');
}

export function renderMigrationReport(
    projectName: string,
    scanResult: ScanResult,
): string {
    const lines: string[] = [];

    lines.push(`# Migration Report — ${projectName}`);
    lines.push('_Generated by stackmoss inject. Reviewed by human before promote._');
    lines.push('');

    lines.push('## FACTS (confidence: high)');
    lines.push('> Những gì đã được verify từ file thực tế trong repo.');
    lines.push('');

    if (scanResult.facts.length === 0) {
        lines.push('_No facts detected — this repo may be empty or have no recognizable config files._');
    } else {
        for (const fact of scanResult.facts) {
            lines.push(`- **${fact.category}:** ${fact.value} (from ${fact.source})`);
        }
    }
    lines.push('');

    lines.push('## HYPOTHESES (confidence: medium, cần verify)');
    lines.push('> Những gì StackMoss suy đoán nhưng chưa chắc.');
    lines.push('');

    if (scanResult.hypotheses.length === 0) {
        lines.push('_No hypotheses generated._');
    } else {
        for (const hypothesis of scanResult.hypotheses) {
            const criticalTag = hypothesis.critical ? ' ⚠️ CRITICAL' : '';
            lines.push(
                `- **${hypothesis.category}:** ${hypothesis.value} ` +
                `(confidence: ${hypothesis.confidence}%)${criticalTag} — from ${hypothesis.source}`,
            );
        }
    }
    lines.push('');

    lines.push('## OPEN QUESTIONS (cần human confirm trước khi promote)');
    lines.push('');

    const unresolvedQuestions = scanResult.openQuestions.filter((question) => !question.resolved);
    const resolvedQuestions = scanResult.openQuestions.filter((question) => question.resolved);

    if (unresolvedQuestions.length === 0 && resolvedQuestions.length === 0) {
        lines.push('_No open questions — all clear for promote._');
    } else {
        for (const question of unresolvedQuestions) {
            lines.push(`- [ ] **[${question.id}]** ${question.text} _(${question.impact})_`);
        }

        if (resolvedQuestions.length > 0) {
            lines.push('');
            lines.push('### Đã trả lời');
            for (const question of resolvedQuestions) {
                lines.push(`- [x] **[${question.id}]** ${question.text} → ${question.answer ?? '(confirmed)'}`);
            }
        }
    }
    lines.push('');

    lines.push('---');
    lines.push('');
    lines.push('_Sau khi resolve hết OPEN QUESTIONS → chạy `stackmoss promote --confirm`_');
    lines.push('');

    return lines.join('\n');
}

export interface ParsedReport {
    hasUnresolvedQuestions: boolean;
    unresolvedCount: number;
    resolvedCount: number;
    hasCriticalLowConfidence: boolean;
    rawContent: string;
}

export function parseMigrationReport(content: string): ParsedReport {
    const openQuestionsSection = getSection(content, 'OPEN QUESTIONS');
    const hypothesesSection = getSection(content, 'HYPOTHESES');

    const unresolvedCount = (openQuestionsSection.match(/^- \[ \] \*\*\[/gm) ?? []).length;
    const resolvedCount = (openQuestionsSection.match(/^- \[x\] \*\*\[/gm) ?? []).length;

    let hasCriticalLowConfidence = false;
    const lines = hypothesesSection.split('\n');
    for (const line of lines) {
        if (!line.includes('CRITICAL')) {
            continue;
        }

        const confidenceMatch = line.match(/confidence:\s*(\d+(?:\.\d+)?)%/i);
        if (!confidenceMatch) {
            continue;
        }

        const confidence = Number.parseFloat(confidenceMatch[1]);
        if (confidence < 80) {
            hasCriticalLowConfidence = true;
            break;
        }
    }

    return {
        hasUnresolvedQuestions: unresolvedCount > 0,
        unresolvedCount,
        resolvedCount,
        hasCriticalLowConfidence,
        rawContent: content,
    };
}
